import coverage from "@/data/data-coverage.json";
import type { DataCoverage, DataCoverageSource } from "@/lib/types";

/** Freshness boundaries as generated by the research engine. Nothing here is
 * hand-entered: every date comes from the last observation actually present in
 * the corresponding source. */
export const dataCoverage = coverage as unknown as DataCoverage;

export function coverageSource(id: DataCoverageSource["id"]) {
  return dataCoverage.sources.find((s) => s.id === id);
}

/** Length of the backtest sample in whole years, used where the interface
 * describes the span in prose. */
export function sampleYears(): number {
  const start = new Date(dataCoverage.backtestStart + "T00:00:00").getTime();
  const end = new Date(dataCoverage.backtestEnd + "T00:00:00").getTime();
  return Math.floor((end - start) / (365.2425 * 24 * 60 * 60 * 1000));
}
