import { getMetric } from "@/lib/data/metrics";
import { formatDate } from "@/lib/formatters";
import { SHORT_NAMES, STRATEGY_COLORS, STRATEGY_ORDER } from "@/lib/chart-utils";
import RegimeRibbon from "@/components/layout/RegimeRibbon";

const SPECS: [string, string][] = [
  ["Universe", "13 ETF proxies"],
  ["Rules", "4 allocation methods"],
  ["Benchmarks", "SPY + 60/40"],
  ["Rebalance", "Monthly"],
  ["Costs", "5 bps × turnover"],
  ["Lookbacks", "6M / 1Y / 3Y"],
];

/** Opening frame. The regime record is the identity: the title states the
 * subject, the ribbon shows it, and a fixed-color key introduces the four
 * rules that the rest of the interface tracks. */
export default function ResearchAbstract() {
  const sample = getMetric("Equal Weight", "1Y");
  const dataThrough = sample ? formatDate(sample.endDate) : "";

  return (
    <section id="premise-opening" className="pb-4 pt-8 sm:pt-12">
      <h1 className="font-display max-w-[880px] text-[31px] font-semibold leading-[1.05] tracking-[-0.02em] text-ink sm:text-[42px]">
        Four allocation rules, three crisis windows, eighteen years of regime change.
      </h1>
      <p className="mt-4 max-w-[620px] text-[15px] leading-relaxed text-ink-secondary">
        Equal Weight, minimum variance, Max Sharpe, and a rule-based
        regime-aware allocation are run on identical data, constraints, and
        costs. The question is not which wins, but how each behaves when
        diversification assumptions stop holding.
      </p>

      <figure className="mt-10">
        <figcaption className="mb-2 flex items-baseline justify-between">
          <span className="text-[12px] font-semibold text-ink">
            The regime record
          </span>
          <span className="font-mono text-[11px] text-ink-faint">
            2007 to {dataThrough}
          </span>
        </figcaption>
        <RegimeRibbon variant="full" />
      </figure>

      <div className="mt-9 grid gap-x-10 gap-y-6 lg:grid-cols-[minmax(0,1fr)_300px]">
        <dl className="grid grid-cols-2 gap-px overflow-hidden border border-border-soft bg-border-soft sm:grid-cols-3">
          {SPECS.map(([label, value]) => (
            <div key={label} className="bg-panel px-3.5 py-2.5">
              <dt className="text-[10.5px] font-medium text-ink-faint">{label}</dt>
              <dd className="tabular mt-0.5 font-mono text-[12.5px] text-ink">{value}</dd>
            </div>
          ))}
        </dl>

        <div>
          <span className="text-[10.5px] font-medium uppercase tracking-[0.12em] text-ink-faint">
            Rules tracked throughout
          </span>
          <ul className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1.5">
            {STRATEGY_ORDER.map((s) => (
              <li key={s} className="flex items-center gap-2 text-[12px] text-ink-secondary">
                <span
                  aria-hidden
                  className="h-2.5 w-2.5 shrink-0"
                  style={{ backgroundColor: STRATEGY_COLORS[s] }}
                />
                {SHORT_NAMES[s]}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <p className="mt-5 max-w-[760px] text-[11.5px] leading-relaxed text-ink-faint">
        Daily adjusted closes 2007 to {dataThrough}, FRED CPI, Cboe VIX, and
        Fama-French factors. Monthly rolling backtests with no look-ahead; every
        figure below is generated by the Python research engine.
      </p>
    </section>
  );
}
