import RegimeRibbon from "@/components/layout/RegimeRibbon";
import ValidationLedger from "@/components/layout/ValidationLedger";
import { coverageSource, dataCoverage } from "@/lib/data/coverage";
import type { DataCoverageSource } from "@/lib/types";

/** Source descriptions stay hand-written; the coverage date beside each one is
 * generated, so the colophon states four honest boundaries rather than
 * implying every series is current through the same day. */
const SOURCE_LINES: [DataCoverageSource["id"], string][] = [
  ["etf-prices", "ETF prices, Yahoo Finance adjusted close"],
  ["vix", "VIX, Yahoo Finance / Cboe"],
  ["cpi", "CPI, FRED CPIAUCSL"],
  ["fama-french", "Factors, Kenneth French Data Library"],
];

/** Colophon: the ribbon closes the document as it opened it, over a structured
 * record of sources, method, and validation. The disclaimer sits once at the
 * base. */
export default function ProjectFooter() {
  return (
    <footer className="mt-6 border-t-2 border-ink pt-8">
      <RegimeRibbon variant="marker" className="mb-8" />

      <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_auto]">
        <div className="grid gap-8 sm:grid-cols-3">
          <div>
            <span className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-ink-faint">
              Data sources
            </span>
            <ul className="mt-2 space-y-1 text-[11.5px] text-ink-muted">
              {SOURCE_LINES.map(([id, text]) => (
                <li key={id}>
                  {text}
                  <span className="tabular block font-mono text-[10.5px] text-ink-faint">
                    through {coverageSource(id)?.throughLabel}
                  </span>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <span className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-ink-faint">
              Method
            </span>
            <ul className="mt-2 space-y-1 text-[11.5px] text-ink-muted">
              <li>Monthly rolling backtests, no look-ahead</li>
              <li>6M / 1Y / 3Y estimation lookbacks</li>
              <li>5 bps transaction cost per turnover</li>
              <li>All figures generated by the engine</li>
              <li className="tabular font-mono text-[10.5px] text-ink-faint">
                Backtest sample {dataCoverage.backtestStart} to{" "}
                {dataCoverage.backtestEnd} ({dataCoverage.tradingDays} days)
              </li>
            </ul>
          </div>
          <div>
            <span className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-ink-faint">
              Build
            </span>
            <ul className="mt-2 space-y-1 text-[11.5px] text-ink-muted">
              <li>Vatsal Maniar</li>
              <li>Python research engine</li>
              <li>Next.js frontend</li>
              <li>
                <a
                  href="https://github.com/VM25/portfolio-lab"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline decoration-border-strong underline-offset-2 transition-colors hover:text-strat-gmv"
                >
                  Source on GitHub
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div className="lg:w-[260px]">
          <ValidationLedger compact />
        </div>
      </div>

      <p className="mt-9 border-t border-border-soft pt-5 text-[11.5px] leading-relaxed text-ink-faint">
        This analysis is for research and educational demonstration only. It is
        not investment advice and does not recommend any portfolio, ETF,
        security, or trading strategy. Historical performance does not predict
        future results.
      </p>
      <div className="mt-3 flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1 pb-10">
        <p className="text-[12px] font-semibold text-ink">
          Portfolio Risk &amp; Allocation Analytics
        </p>
        <a
          href="https://github.com/VM25/portfolio-lab"
          target="_blank"
          rel="noopener noreferrer"
          className="font-mono text-[11.5px] text-ink-muted underline decoration-border-strong underline-offset-2 transition-colors hover:text-strat-gmv"
        >
          github.com/VM25/portfolio-lab
        </a>
      </div>
    </footer>
  );
}
